using System.Collections.Generic;
using UnityEngine;

namespace Core
{
    public static class KeyCodeTranslator
    {
        public static Dictionary<KeyCode, string> Russian = new Dictionary<KeyCode, string>()
        {
            [KeyCode.Space] = " ",
            [KeyCode.BackQuote] = "Ё",
            [KeyCode.Q] = "Й",
            [KeyCode.W] = "Ц",
            [KeyCode.E] = "У",
            [KeyCode.R] = "К",
            [KeyCode.T] = "Е",
            [KeyCode.Y] = "Н",
            [KeyCode.U] = "Г",
            [KeyCode.I] = "Ш",
            [KeyCode.O] = "Щ",
            [KeyCode.P] = "З",
            [KeyCode.LeftBracket] = "Х",
            [KeyCode.RightBracket] = "Ъ",
            [KeyCode.A] = "Ф",
            [KeyCode.S] = "Ы",
            [KeyCode.D] = "В",
            [KeyCode.F] = "А",
            [KeyCode.G] = "П",
            [KeyCode.H] = "Р",
            [KeyCode.J] = "О",
            [KeyCode.K] = "Л",
            [KeyCode.L] = "Д",
            [KeyCode.Semicolon] = "Ж",
            [KeyCode.Quote] = "Э",
            [KeyCode.Z] = "Я",
            [KeyCode.X] = "Ч",
            [KeyCode.C] = "С",
            [KeyCode.V] = "М",
            [KeyCode.B] = "И",
            [KeyCode.N] = "Т",
            [KeyCode.M] = "Ь",
            [KeyCode.Comma] = "Б",
            [KeyCode.Period] = "Ю",
            [KeyCode.Alpha0] = "0",
            [KeyCode.Alpha1] = "1",
            [KeyCode.Alpha2] = "2",
            [KeyCode.Alpha3] = "3",
            [KeyCode.Alpha4] = "4",
            [KeyCode.Alpha5] = "5",
            [KeyCode.Alpha6] = "6",
            [KeyCode.Alpha7] = "7",
            [KeyCode.Alpha8] = "8",
            [KeyCode.Alpha9] = "9",
            [KeyCode.Keypad0] = "0",
            [KeyCode.Keypad1] = "1",
            [KeyCode.Keypad2] = "2",
            [KeyCode.Keypad3] = "3",
            [KeyCode.Keypad4] = "4",
            [KeyCode.Keypad5] = "5",
            [KeyCode.Keypad6] = "6",
            [KeyCode.Keypad7] = "7",
            [KeyCode.Keypad8] = "8",
            [KeyCode.Keypad9] = "9"
        };

        public static Dictionary<KeyCode, string> English = new Dictionary<KeyCode, string>()
        {
            [KeyCode.Space] = " ",
            [KeyCode.Q] = "Q",
            [KeyCode.W] = "W",
            [KeyCode.E] = "E",
            [KeyCode.R] = "R",
            [KeyCode.T] = "T",
            [KeyCode.Y] = "Y",
            [KeyCode.U] = "U",
            [KeyCode.I] = "I",
            [KeyCode.O] = "O",
            [KeyCode.P] = "P",
            [KeyCode.A] = "A",
            [KeyCode.S] = "S",
            [KeyCode.D] = "D",
            [KeyCode.F] = "F",
            [KeyCode.G] = "G",
            [KeyCode.H] = "H",
            [KeyCode.J] = "J",
            [KeyCode.K] = "K",
            [KeyCode.L] = "L",
            [KeyCode.Z] = "Z",
            [KeyCode.X] = "X",
            [KeyCode.C] = "C",
            [KeyCode.V] = "V",
            [KeyCode.B] = "B",
            [KeyCode.N] = "N",
            [KeyCode.M] = "M",
            [KeyCode.Alpha0] = "0",
            [KeyCode.Alpha1] = "1",
            [KeyCode.Alpha2] = "2",
            [KeyCode.Alpha3] = "3",
            [KeyCode.Alpha4] = "4",
            [KeyCode.Alpha5] = "5",
            [KeyCode.Alpha6] = "6",
            [KeyCode.Alpha7] = "7",
            [KeyCode.Alpha8] = "8",
            [KeyCode.Alpha9] = "9",
            [KeyCode.Keypad0] = "0",
            [KeyCode.Keypad1] = "1",
            [KeyCode.Keypad2] = "2",
            [KeyCode.Keypad3] = "3",
            [KeyCode.Keypad4] = "4",
            [KeyCode.Keypad5] = "5",
            [KeyCode.Keypad6] = "6",
            [KeyCode.Keypad7] = "7",
            [KeyCode.Keypad8] = "8",
            [KeyCode.Keypad9] = "9"
        };

    }
}
